<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ActualSalaryMonthResource\Pages;
use App\Models\ActualSalaryMonth;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;

class ActualSalaryMonthResource extends Resource
{
    protected static ?string $model = ActualSalaryMonth::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';
    protected static ?string $label = 'راتب     ';
    protected static ?string $pluralLabel = '  الرواتب   المستحقة لهذا الشهر';
    protected static ?string $navigationGroup = " التقارير الشهرية";

    protected static function getNavigationBadge(): ?string
    {
        return ActualSalaryMonth::count(); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make("id")->label("ID")->sortable(),
                Tables\Columns\TextColumn::make("employee.name")->label("الموظف")->searchable(),
                Tables\Columns\BadgeColumn::make("total")->label("الراتب المستحق")->sortable(),
                Tables\Columns\BadgeColumn::make("employee.bank_no")->label("بطاقة البنك")->sortable(),

            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListActualSalaryMonths::route('/'),
            'create' => Pages\CreateActualSalaryMonth::route('/create'),
            'edit' => Pages\EditActualSalaryMonth::route('/{record}/edit'),
        ];
    }
}
