<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReportMonth extends Report
{
    use HasFactory;

    protected $guarded = [];
    protected $table = "reports";

    protected static function booted()
    {
        static::addGlobalScope('created_at', function (Builder $builder) {
            $builder->whereMonth('created_at', Carbon::now()->month);
        });
        parent::booted(); // TODO: Change the autogenerated stub
    }
}
